document.addEventListener('DOMContentLoaded', () => {
    
    // --- Theme Toggling ---
    const themeBtn = document.getElementById('theme-toggle');
    const body = document.body;
    const icon = themeBtn.querySelector('i');

    // Check saved theme
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme === 'light') {
        body.classList.remove('dark-mode');
        icon.classList.remove('fa-sun');
        icon.classList.add('fa-moon');
    }

    themeBtn.addEventListener('click', () => {
        body.classList.toggle('dark-mode');
        
        if (body.classList.contains('dark-mode')) {
            localStorage.setItem('theme', 'dark');
            icon.classList.remove('fa-moon');
            icon.classList.add('fa-sun');
        } else {
            localStorage.setItem('theme', 'light');
            icon.classList.remove('fa-sun');
            icon.classList.add('fa-moon');
        }
    });

    // --- News Loading & Rendering ---
    const newsGridContainer = document.getElementById('news-grid-container');
    const featuredNewsContainer = document.getElementById('featured-news-container');
    const filterBtns = document.querySelectorAll('.filter-btn');
    
    let allNewsData = [];

    // Fetch news data
    async function loadNews() {
        try {
            // In a real scenario, this fetches the JSON generated by our backend node script
            const response = await fetch('data/news.json');
            
            if (!response.ok) {
                throw new Error('News file not found or empty.');
            }
            
            allNewsData = await response.json();
            
            // Sort by published date (newest first)
            allNewsData.sort((a, b) => new Date(b.pubDate) - new Date(a.pubDate));

            renderNews(allNewsData);
            
        } catch (error) {
            console.error("Error loading news:", error);
            // Fallback for development/testing when JSON isn't generated yet
            renderDemoData();
        }
    }

    // Render news cards
    function renderNews(newsArray) {
        if (newsArray.length === 0) {
            newsGridContainer.innerHTML = '<p style="text-align:center; width:100%;">کوئی خبر نہیں ملی۔</p>';
            featuredNewsContainer.innerHTML = '';
            return;
        }

        // 1. Render Featured News (Top 1)
        const featured = newsArray[0];
        featuredNewsContainer.innerHTML = `
            <div class="glass" style="padding: 20px; width: 100%;">
                <div class="card-meta">
                    <span class="source-badge">${featured.source || 'عالمی'}</span>
                    <span>${formatDate(featured.pubDate)}</span>
                </div>
                <h3 class="card-title" style="font-size: 1.8rem; margin-top: 10px;">
                    <a href="${featured.link}" target="_blank">${featured.urduTitle}</a>
                </h3>
                <p class="card-excerpt" style="-webkit-line-clamp: 4;">${featured.urduSummary}</p>
                <div style="margin-top: 20px;">
                    <a href="${featured.link}" target="_blank" class="read-more">مزید پڑھیں <i class="fas fa-arrow-left"></i></a>
                </div>
            </div>
        `;

        // 2. Render Grid News (The rest)
        newsGridContainer.innerHTML = ''; // Clear loading
        
        const gridNews = newsArray.slice(1);
        
        gridNews.forEach(news => {
            const article = document.createElement('article');
            article.className = 'glass news-card';
            
            // Generate a random image placeholder for layout aesthetics 
            // In real app, we extract image from RSS feed
            const imgUrl = news.imageUrl || `https://source.unsplash.com/random/400x200?news,${news.category || 'world'}&sig=${Math.random()}`;

            article.innerHTML = `
                <!-- <img src="${imgUrl}" alt="News Image" class="card-image" loading="lazy"> -->
                <div class="card-content">
                    <div class="card-meta">
                        <span class="source-badge">${news.source || 'News'}</span>
                        <span>${formatDate(news.pubDate)}</span>
                    </div>
                    <h3 class="card-title">
                        <a href="${news.link}" target="_blank">${news.urduTitle}</a>
                    </h3>
                    <p class="card-excerpt">${news.urduSummary}</p>
                    <div class="card-footer">
                        <a href="${news.link}" target="_blank" class="read-more">پوری خبر <i class="fas fa-arrow-left"></i></a>
                    </div>
                </div>
            `;
            newsGridContainer.appendChild(article);
        });
    }

    // Filter functionality
    filterBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            // Update active state
            filterBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');

            const filterType = btn.getAttribute('data-filter');
            
            if (filterType === 'all') {
                renderNews(allNewsData);
            } else {
                const filtered = allNewsData.filter(n => 
                    n.category && n.category.toLowerCase() === filterType.toLowerCase()
                );
                renderNews(filtered);
            }
        });
    });

    // Helper: Format Date for Urdu audience
    function formatDate(dateString) {
        if (!dateString) return '';
        const date = new Date(dateString);
        return date.toLocaleDateString('ur-PK', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
    }

    // Fallback Mock Data for UI Testing before backend is ready
    function renderDemoData() {
        console.log("Using Mock Data for UI Testing...");
        const mockData = [
            {
                urduTitle: "مصنوعی ذہانت: محققین نے ایک نیا اور تیز ترین AI ماڈل متعارف کروا دیا",
                urduSummary: "دنیا بھر کے سائنسدانوں نے ایک ایسا نیا ماڈل تیار کیا ہے جو روایتی سسٹمز کے مقابلے میں 10 گنا زیادہ تیزی سے کام کرتا ہے۔ اس سے طب اور انجینئرنگ میں انقلاب آ سکتا ہے۔",
                source: "BBC Tech",
                link: "#",
                pubDate: new Date().toISOString(),
                category: "tech"
            },
            {
                urduTitle: "عالمی منڈی میں تیل کی قیمتوں میں نمایاں کمی",
                urduSummary: "مشرق وسطیٰ میں کشیدگی کے باوجود عالمی سطح پر تیل کی قیمتوں میں 5 فیصد تک کمی دیکھی گئی ہے جس سے ترقی پذیر ممالک کو ریلیف ملنے کا امکان ہے۔",
                source: "Al Jazeera",
                link: "#",
                pubDate: new Date(Date.now() - 86400000).toISOString(),
                category: "world"
            },
            {
                urduTitle: "کرکٹ ورلڈ کپ: فائنل میں سنسنی خیز مقابلے کے بعد فتح",
                urduSummary: "کل رات کھیلے گئے فائنل میچ میں آخری اوور تک سسپنس برقرار رہا۔ فاتح ٹیم نے تاریخی کارکردگی کا مظاہرہ کرتے ہوئے ٹرافی اپنے نام کر لی۔",
                source: "CNN Sports",
                link: "#",
                pubDate: new Date(Date.now() - 172800000).toISOString(),
                category: "sports"
            },
            {
                urduTitle: "مریخ پر پانی کے نئے ذخائر دریافت، سائنسدانوں کا حیران کن دعویٰ",
                urduSummary: "ناسا کی تازہ ترین رپورٹ میں دعویٰ کیا گیا ہے کہ مریخ کی سطح کے نیچے برف کے وسیع ذخائر موجود ہیں، جو مستقبل کے مشنز کے لیے اہم ثابت ہو سکتے ہیں۔",
                source: "Space.com",
                link: "#",
                pubDate: new Date(Date.now() - 259200000).toISOString(),
                category: "tech"
            }
        ];
        allNewsData = mockData;
        renderNews(mockData);
    }

    // Initialize
    loadNews();
});
